# comment

name: Python simple test

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]


jobs:
    build: 

        runs-on: ubuntu-latest

        steps:
        - name: Ola test
          run: python ola.py

